<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "fp_misereor"
 *
 * Auto generated by Extension Builder 2018-07-05
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = [
    'title' => 'Fluid Gallery',
    'description' => 'Erweitert Fluid um eine Galerie-Ansicht.',
    'category' => 'fe',
    'author' => 'Yannik Börgener',
    'author_email' => 'kontakt@boergener.de',
    'state' => 'beta',
    'internal' => '',
    'uploadfolder' => '0',
    'createDirs' => '',
    'clearCacheOnLoad' => 0,
    'version' => '3.1.0',
    'constraints' => [
        'depends' => [
            'typo3' => '10.4.16-10.4.99',
            'php' => '7.4-7.99'
        ],
        'conflicts' => [],
        'suggests' => [],
    ],
];
