# You can simply include this Route in your site configuration:
# imports:
#   - { resource: "EXT:bw_gallery/Configuration/Routes/Default.yaml" }

routeEnhancers:
  BwGallery:
    type: Simple
    routePath: '/{id}/{page}'
    defaults:
      page: 1
    requirements:
      id: '[0-9]{1,5}'
      page: '[0-9]{1,3}'
    _arguments:
      id: 'bwGallery/uid'
      page: 'bwGallery/page'
    aspects:
      id:
        type: PersistedAliasMapper
        tableName: 'tt_content'
        routeFieldName: 'uid'
      page:
        type: StaticRangeMapper
        start: '1'
        end: '999'